version: '3.3'

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
     networks:
        - wordpress-net
     restart: always
   db:
     depends_on:
        - nginx-proxy
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       VIRTUAL_HOST: woocommerce.redaccess.com.mx
     networks:
        - wordpress-net
   wordpress:
     depends_on:
       - db
       - nginx-proxy
     image: wordpress:latest
     expose:
        - "80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       VIRTUAL_HOST: woocommerce.redaccess.com.mx
     networks:
        - wordpress-net
volumes:
    db_data: {}
networks:
    wordpress-net:
